modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0"

[[mods]]
modId="compressedblockspot"
version="${version}"
displayName="Compressed Pots"
description='''压缩方块附属：压缩盆栽与压缩漏斗盆栽。深色陶盆，可种压缩作物/树苗/甘蔗，压缩土壤按等级差提速。'''
authors="Thatgfsj"

[[dependencies.compressedblockspot]]
modId="neoforge"
type="required"
versionRange="[21.11.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.compressedblockspot]]
modId="minecraft"
type="required"
versionRange="[1.21.11,1.21.12)"
ordering="NONE"
side="BOTH"

[[dependencies.compressedblockspot]]
modId="compressedblocks"
type="required"
versionRange="[0.3.0,)"
ordering="NONE"
side="BOTH"
